# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79d80e3f57b3fd505bea1382bb62d72b820bdfc0f78926b14c856695c913d7e9257fbc55df4ff8adc9a61d1dc4b91042e9a810f8e1d97116943decebc823f657

test:
  secret_key_base: 9926f2b7339a50937f7759db0a440960b3503e0bdeb8bfe300cdda90814bff85ef5198e097d5543a79596c13e096dcc24fc7e6a761d4696333768397a71b11af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
